slice_name: Deck.gl Screen grid
description: null
certified_by: null
certification_details: null
viz_type: deck_screengrid
params:
  color_picker:
    a: 1
    b: 0
    g: 255
    r: 14
  datasource: 5__table
  granularity_sqla: null
  grid_size: 20
  groupby: []
  mapbox_style: mapbox://styles/mapbox/dark-v9
  point_radius: Auto
  point_radius_fixed:
    type: fix
    value: 2000
  point_unit: square_m
  row_limit: 5000
  size: count
  spatial:
    latCol: LAT
    lonCol: LON
    type: latlong
  time_grain_sqla: null
  time_range: No filter
  viewport:
    bearing: -4.952916738791771
    latitude: 37.76024135844065
    longitude: -122.41827069521386
    pitch: 4.750411100577438
    zoom: 14.161641703941438
  viz_type: deck_screengrid
query_context: null
cache_timeout: null
uuid: 2ee327ef-8ce4-4176-9f77-87a2139b6a73
version: 1.0.0
dataset_uuid: 87b7b4e7-456e-4a71-9325-cf67e3d08f17
