slice_name: '% Rural'
description: null
certified_by: null
certification_details: null
viz_type: world_map
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_RUR_TOTL_ZS
  num_period_compare: '10'
  row_limit: 50000
  secondary_metric:
    aggregate: SUM
    column:
      column_name: SP_RUR_TOTL
      optionName: _col_SP_RUR_TOTL
      type: DOUBLE
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Rural Population
  show_bubbles: true
  since: '2014-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: world_map
query_context: null
cache_timeout: null
uuid: def0af46-1bcb-4751-bbfd-fa30505139a1
version: 1.0.0
dataset_uuid: ef3a0931-91de-4bb3-a819-c32fe488e58f
