slice_name: World's Pop Growth
description: null
certified_by: null
certification_details: null
viz_type: area
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: now
  viz_type: area
query_context: null
cache_timeout: null
uuid: 700bd0b8-524d-4aa9-adfe-01ee7d8eadbf
version: 1.0.0
dataset_uuid: ef3a0931-91de-4bb3-a819-c32fe488e58f
