slice_name: total_kpi
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  viz_type: big_number_total
  metric: count
  adhoc_filters: []
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 1
  annotation_layers: []
query_context: '{"datasource": {"id": 1, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "columns": [], "metrics": ["count"], "annotation_layers": [], "series_limit": 0,
  "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data": {}}],
  "form_data": {"datasource": "1__table", "viz_type": "big_number_total", "metric":
  "count", "adhoc_filters": [], "header_font_size": 0.4, "subheader_font_size": 0.15,
  "y_axis_format": "SMART_NUMBER", "time_format": "smart_date", "extra_form_data":
  {}, "dashboards": [1], "force": false, "result_format": "json", "result_type": "full"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 23f773bf-e036-4c3d-924c-19b1736324e7
version: 1.0.0
dataset_uuid: edb827ec-6776-42cc-a00d-d2fd92712d8f
