slice_name: Most Populated Countries
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2014-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: table
query_context: null
cache_timeout: null
uuid: af0cda11-add7-4e5a-80a2-353379bef5c3
version: 1.0.0
dataset_uuid: ef3a0931-91de-4bb3-a819-c32fe488e58f
