slice_name: Daily Totals
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - ds
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  time_range: '1983 : 2023'
  viz_type: table
query_context: "{\n    \"datasource\": {\n        \"id\": 2,\n        \"type\": \"\
  table\"\n    },\n    \"queries\": [\n        {\n            \"columns\": [\n   \
  \             \"ds\"\n            ],\n            \"metrics\": [\n             \
  \   {\n                    \"aggregate\": \"SUM\",\n                    \"column\"\
  : {\n                        \"column_name\": \"num\",\n                       \
  \ \"type\": \"BIGINT\"\n                    },\n                    \"expressionType\"\
  : \"SIMPLE\",\n                    \"label\": \"Births\",\n                    \"\
  optionName\": \"metric_11\"\n                }\n            ],\n            \"time_range\"\
  : \"1983 : 2023\"\n        }\n    ],\n    \"result_format\": \"json\",\n    \"result_type\"\
  : \"full\"\n}"
cache_timeout: null
uuid: 57bfc936-d392-429f-997a-ce8f87a3fca1
version: 1.0.0
dataset_uuid: 4e4f93dc-4a5d-413a-ac88-b8263d0da4cc
