slice_name: chart_1
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  viz_type: big_number_total
  slice_id: 1
  metric: count
  adhoc_filters:
  - expressionType: SIMPLE
    subject: is_regular
    operator: ==
    operatorId: IS_TRUE
    comparator: true
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_od3ouaolk7o_w5dqm9kustp
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"is_regular","op":"==","val":true}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["count"],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"big_number_total","slice_id":1,"metric":"count","adhoc_filters":[{"expressionType":"SIMPLE","subject":"is_regular","operator":"==","operatorId":"IS_TRUE","comparator":true,"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_od3ouaolk7o_w5dqm9kustp"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: b9c6f894-7ed2-456c-8e43-670a1e6c0c0c
version: 1.0.0
dataset_uuid: 77cc048c-f8d9-46d0-8d97-f087b42da4cf
