slice_name: Quarterly Sales (By Product Line)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters:
  - clause: WHERE
    subject: order_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  annotation_layers: []
  x_axis_title_margin: 30
  color_scheme: supersetColors
  comparison_type: values
  datasource: 23__table
  groupby:
  - product_line
  label_colors:
    Classic Cars: '#5AC189'
    Motorcycles: '#666666'
    Planes: '#FCC700'
    QuantityOrdered: '#454E7C'
    SUM(Sales): '#1FA8C9'
    Ships: '#A868B7'
    Trains: '#3CCCCB'
    Trucks and Buses: '#E04355'
    Vintage Cars: '#FF7F44'
  y_axis_title_margin: 30
  metrics:
  - aggregate: SUM
    column:
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 917
      is_dttm: false
      optionName: _col_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(Sales)
    optionName: metric_tjn8bh6y44_7o4etwsqhal
    sqlExpression: null
  order_desc: true
  queryFields:
    groupby: groupby
    metrics: metrics
  rich_tooltip: true
  rolling_type: null
  row_limit: 10000
  show_extra_controls: false
  show_legend: true
  slice_id: 2806
  time_compare: null
  time_grain_sqla: P3M
  url_params: {}
  viz_type: echarts_timeseries_bar
  x_axis_time_format: '%m/%d/%Y'
  x_axis_title: Quarter starting
  xAxisLabelRotation: 45
  y_axis_bounds:
  - null
  - null
  y_axis_format: null
  y_axis_title: Revenue ($)
  contributionMode: null
  zoomable: false
  markerEnabled: false
  truncateYAxis: true
  stack: Stack
  x_axis: order_date
query_context: null
cache_timeout: null
uuid: db9609e4-9b78-4a32-87a7-4d9e19d51cd8
version: 1.0.0
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
