slice_name: Pivot Table
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  groupbyColumns:
  - state
  groupbyRows:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: pivot_table_v2
query_context: null
cache_timeout: null
uuid: ea7a86fa-3075-45f8-a903-6d925a7f16de
version: 1.0.0
dataset_uuid: 4e4f93dc-4a5d-413a-ac88-b8263d0da4cc
