slice_name: Genders
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - gender
  limit: '25'
  markup_type: markdown
  metric: sum__num
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: pie
query_context: null
cache_timeout: null
uuid: 3c76580e-ac6c-4cb3-b741-f53b3a711d55
version: 1.0.0
dataset_uuid: 4e4f93dc-4a5d-413a-ac88-b8263d0da4cc
