slice_name: Growth Rate
description: null
certified_by: null
certification_details: null
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  num_period_compare: '10'
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: line
query_context: null
cache_timeout: null
uuid: e44e4dcb-89f7-4dca-97b8-fbc591e4e161
version: 1.0.0
dataset_uuid: ef3a0931-91de-4bb3-a819-c32fe488e58f
