slice_name: Names Sorted by Num in California
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50
  time_range: '100 years ago : now'
  timeseries_limit_metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  viz_type: table
query_context: null
cache_timeout: null
uuid: 176470e4-c178-413b-ba1e-fbe4c59b1afd
version: 1.0.0
dataset_uuid: 4e4f93dc-4a5d-413a-ac88-b8263d0da4cc
