slice_name: How do you prefer to work?
description: null
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_v65f0j14bk_35oi0g94srk
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: is_software_dev
  - clause: WHERE
    comparator: 'NULL'
    expressionType: SIMPLE
    filterOptionName: filter_qb5ionb8wcq_ki4aimey4do
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: school_degree
  - clause: WHERE
    comparator: 'NULL'
    expressionType: SIMPLE
    filterOptionName: filter_3n0z71frg5c_xqnl179to7
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: job_pref
  - clause: WHERE
    subject: time_start
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  x_axis: job_pref
  groupby: school_degree
  bottom_margin: auto
  datasource: 42__table
  left_margin: auto
  linear_color_scheme: blue_white_yellow
  metric: count
  normalize_across: heatmap
  queryFields:
    metric: metrics
  row_limit: null
  show_legend: true
  show_percentage: true
  slice_id: 1367
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  url_params: {}
  viz_type: heatmap_v2
  xscale_interval: null
  value_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  yscale_interval: null
  annotation_layers: []
  legend_type: continuous
query_context: null
cache_timeout: null
uuid: cb8998ab-9f93-4f0f-4e4b-3bfe4b0dea9d
version: 1.0.0
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
