slice_name: Num Births Trend
description: null
certified_by: null
certification_details: null
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: line
query_context: null
cache_timeout: null
uuid: a0305317-115c-4839-8943-7ac37dad21d0
version: 1.0.0
dataset_uuid: 4e4f93dc-4a5d-413a-ac88-b8263d0da4cc
